container:
  image : unriginal/clang-build:latest

Build&Test_task:
  script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - mkdir build
    - cd build
    - cmake ../
    - make
    - ./test_module --success
