image : unriginal/clang-build:latest

before_script:
    - apt-get update -y
    - apt-get install -y cmake

Build&Test:
  script:
    - cd ./tests
    - mkdir build
    - cd build
    - cmake ../
    - make
    - ./test_module --success
