image : unriginal/clang-build:latest

pipelines:
  default:
    - step:
      script:
        - apt-get update --y
        - apt-get install --y cmake
	- cd ./tests
        - mkdir build
        - cd build
        - cmake ../
        - make
        - ./test_module --success
